#!/usr/bin/env bash
# Update package lists
apt-get update -y

# Install Nginx silently
apt-get install nginx -y

# Create simple HTML page with required string
echo "<html><head></head><body>Holberton School for the win!</body></html>" > /var/www/html/index.html

# Restart nginx using service (not systemctl)
service nginx restart
