#!/usr/bin/env bash
# Update package lists
apt-get update -y

# Install Nginx silently
apt-get install nginx -y

# Replace default page with custom message
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Restart nginx using service (not systemctl)
service nginx restart
